### PR TITLE
ASM-5170 Recursive alias when transport is required multiple times

### PR DESCRIPTION
**Pull request by asaenz**
This is the fix that @ripienaar suggested.  @ksw2599 tested and it seemed to be working.

### CODE REVIEW

**Comment by aimers1975** [comment]
@ripienaar or @gavin-scott Can one of your review and merge?

**Comment by ripienaar** [comment]
I can't merge (no permission), @gavin-scott will have to

**Comment by gavin-scott** [comment]
@asaenz were you going to submit a PR to remove the transport from vmware-vmware_lib? We talked about needing to do that since they were slightly different and we don't know which one is getting loaded.

**Comment by gavin-scott** [comment]
@ripienaar I fixed the permissions on the repo in the unlikely even that we need more changes here ;-)

**Comment by asaenz** [comment]
@gavin-scott Yes, I forgot about that.  I'll take care of it this morning.

**Pull request merged**
